# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'

- script: |
    echo Download Unified Agent
    curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
    echo Start Scan The Job With WhiteSource
    java -jar wss-unified-agent.jar -d $(Pipeline.Workspace)
  displayName: 'Scan The Job With Mend Unified Agent'
  env:
    WS_APIKEY: $(APIKEY)
    WS_USERKEY: $(USERKEY)
    WS_WSS_URL: 'https://saas.whitesourcesoftware.com/agent'
    WS_PRODUCTNAME: AsheAzure
    WS_PROJECTNAME: AZDO_CICD_Integrate
    WS_RESOLVEALLDEPENDENCIES: true

    curl -L -g -X POST "https://saas.whitesourcesoftware.com/api/v1.4" -H "Content-Type: application/json" -d "{\"requestType\":\"getProjectRiskReport\",\"userKey\":\"" + $(USERKEY) +"\",\"projectToken\":\"690cb9506a58402d98ee98a4f25a8be9a6bd99a35525430d8855d80dc65ba302\"}"
